apiVersion: apps.emqx.io/v1beta3
kind: EmqxBroker
metadata:
  name: emqx
  namespace: "emqx-operator-system"
spec:
  replicas: 6
  emqxTemplate:
   # image: emqx/emqx:5.0.6
    image: emqx/emqx:4.4.6
 #   config:
 #     listener.tcp.external: 0.0.0.0:1883
 #     management.listener.http: 0.0.0.0:8081
 #     dashboard.listener.http: 0.0.0.0:18083 
  #  resources:
  #    limits:
  #      cpu: 500m
  #      memory: 200Mi
  #    requests:
  #      cpu: 500m
  #      memory: 100Mi
    securityContext:
      sysctls:
        #- name: fs.file-max
       #   value: "2097152"
       # - name: fs.nr_open
      #    value: "2097152"
      #  - name: net.core.somaxconn
      #    value: "32768"
      #  - name: net.ipv4.tcp_max_syn_backlog
      #    value: "16384"
       # - name: net.core.netdev_max_backlog
       #   value: "16384"
        - name: net.ipv4.ip_local_port_range
          value: "1024 65000"
      #  - name: net.core.rmem_default
      #    value: "262144"
      #  - name: net.core.wmem_default
      #    value: "262144"
       # - name: net.core.rmem_max
      #    value: "16777216"
      #  - name: net.core.wmem_max
       #   value: "16777216"
       # - name: net.core.optmem_max
      #    value: "16777216"
      #  - name: net.ipv4.tcp_rmem
      #    value: "1024 4096 16777216"
      #  - name: net.ipv4.tcp_wmem
     #     value: "1024 4096 16777216"
      #  - name: net.ipv4.tcp_max_tw_buckets
      #    value: "1048576"
      #  - name: net.ipv4.tcp_fin_timeout
      #    value: "15"
    serviceTemplate:
      spec:
        type: LoadBalancer
        ports:
        -  name: mqtt
           protocol: "TCP"
           port: 1883
    acl:
      - "{allow, all}."
